### ISSUE TITLE
Kicad problem, missing resources?

### ISSUE THREAD

**Issue by jimmyw** [fishpepper/tinyFISH#1]
I was trying to open and view the schema, and was met with this:

```
The following libraries were not found:
tinyFISH-rescue
special
```

If i try open the pcb layout i get this:

```
Error loading board.
KiCad was unable to open this file, as it was created with a more recent version than the one you are running. To open it, you'll need to upgrade KiCad to a more recent version.

Date of KiCad version required (or newer): 2016-08-15

Full error text:
PARSE_ERROR: Expecting 'clearance, trace_width, via_dia, via_drill, uvia_dia, uvia_drill, or add_net' in input/source
'/Users/jimmy/tinyFISH/tinyFISH.kicad_pcb'
line 199
offset 6
from /Users/ansible/4.0.5/kicad-mac-packaging-4.0.0/kicad/common/dsnlexer.cpp : Expecting() : line 369
```

I have not been using kicad before, just curious how your schemetics looks like.

I am using kicad 4.0.5 on mac.

**Comment by fishpepper** [comment]
I accidently edited the files when i was binaries compiled from kicad master...
You will need a more recent version from kicad. I compiled my own binaries from kicad commit efdfaeb.

**Comment by vcazan** [comment]
I am having troubles building kicad, is there any way you can release some gerbs so I can order from pcbway?

EDIT: I just installed a nightly and it worked no problem. Sorry about that :)

http://downloads.kicad-pcb.org/windows/nightly/
