### ISSUE TITLE
schematic

### ISSUE THREAD

**Issue by silver13** [fishpepper/tinyFISH#3]
Sorry to be annoying by using issues, but is there a schematic in jpg/pdf format?

I installed KiCad but that did not open the files correctly, something about version.

Additionally, do you know of a reception issue, seems to happen most at about half throttle so I assume it's caused by noise (from escs) affecting the receiver chip, which is why I need the schematic.

Thanks for your great work.

**Comment by TinYOneGit** [comment]
@silver13 
You may want to try the KiCad nightly build (kicad-r8145.d37a33723-x86_64), I had issue opening the files when using the stable build (kicad-4.0.6-x86_64).

Also remember to get a copy of the kicad_misc folder from the repository (i.e. git submodule init; git submodule update)

Hope this helps :)

**Comment by silver13** [comment]
Cool, I can see it now, thanks.

What range is the rx supposed to have, I haven't used frsky before...

**Comment by silver13** [comment]
I think I figured out the reason for rx issues, it's caused by the vreg. It's pnp based, of the type where the input should be always higher compared to the output. Because it has a diode across.

When escs draw current and voltage drops, it make the diode conduct, which disrupts regulation.

Should be fixable by different regulator type ( fet based ldo)

Anyway, just in case you didn't know.
